#include "Demo_MessageBox/ScreenMain/ScreenMain.h"
#include "Demo_MessageBox/Demo_MessageBox.h"

#include "Resource/Plugin/lvgl_plugin.h"
/**********************
 *       WIDGETS
 **********************/

/**********************
 *  STATIC VARIABLES
 **********************/
lv_obj_t* message_box_1_scr_screenmain;
lv_obj_t* button_resume_scr_screenmain;
lv_obj_t* container_1_scr_screenmain;
lv_obj_t* label_1_scr_screenmain;
lv_obj_t* label_2_scr_screenmain;

lv_obj_t* ScreenMain_create(){
	lv_obj_t *parent = lv_plugin_scr_create();
	lv_obj_set_event_cb(parent, ScreenMain_event_callback);

	_lv_obj_set_style_local_color(parent,0,LV_STYLE_BG_COLOR,COLOR_PICK(0xef,LV_COLOR_MAKE(233,233,233)));
	if(COLOR_PICK(0xef,LV_COLOR_MAKE(233,233,233)).full== LV_COLOR_TRANSP.full){
		_lv_obj_set_style_local_opa(parent,0,LV_STYLE_BG_OPA,0);
	}

	static lv_style_t message_box_1_s0;
	lv_style_init(&message_box_1_s0);
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_font(&message_box_1_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0xcd,LV_COLOR_MAKE(31,72,154)));
	lv_style_set_bg_grad_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_outline_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_shadow_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x9,LV_COLOR_MAKE(192,192,192)));
	lv_style_set_text_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_text_sel_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	static lv_style_t message_box_1_s1;
	lv_style_init(&message_box_1_s1);
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_bg_color(&message_box_1_s1,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s1,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s1,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	static lv_style_t message_box_1_s2;
	lv_style_init(&message_box_1_s2);
	lv_style_set_radius(&message_box_1_s2,LV_STATE_DEFAULT,10);
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_border_width(&message_box_1_s2,LV_STATE_DEFAULT,3);
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_width(&message_box_1_s2,LV_STATE_DEFAULT,0);
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_value_font(&message_box_1_s2,LV_STATE_DEFAULT,&lv_font_montserrat_16);
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_font(&message_box_1_s2,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(1,162,177)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x6,LV_COLOR_MAKE(255,255,0)));
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_opa(&message_box_1_s2,LV_STATE_FOCUSED,127);
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0xbc,LV_COLOR_MAKE(200,250,231)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0x6,LV_COLOR_MAKE(255,255,0)));
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&message_box_1_s2,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_obj_t *message_box_1 = lv_msgbox_create(parent, NULL);
	lv_obj_set_hidden(message_box_1, false);
	lv_obj_set_click(message_box_1, true);
	lv_obj_set_drag(message_box_1, false);
	lv_obj_set_pos(message_box_1, 65, 64);
	lv_obj_set_size(message_box_1, 200, 114);
	lv_plugin_msgbox_allocate_ext_attr(message_box_1);
	lv_msgbox_set_text(message_box_1,"Demo MessageBox");
	lv_msgbox_set_anim_time(message_box_1, 500);
	lv_msgbox_set_recolor(message_box_1, false);
	static const char* message_box_1_LVGLPropertyMsgBoxBtnmatrixButtonsText[] = {"OK","NO","",""};
	lv_msgbox_add_btns(message_box_1, message_box_1_LVGLPropertyMsgBoxBtnmatrixButtonsText);
	lv_obj_add_style(message_box_1, 0, &message_box_1_s0);
	lv_obj_add_style(message_box_1, 64, &message_box_1_s1);
	lv_obj_add_style(message_box_1, 65, &message_box_1_s2);

	message_box_1_scr_screenmain = message_box_1;
	lv_obj_set_event_cb(message_box_1_scr_screenmain, msgbox_event_callback);


	static lv_style_t button_resume_s0;
	lv_style_init(&button_resume_s0);
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	static char* button_resume_LV_STYLE_VALUE_STR_part_0_state_0 = "Resume";

	lv_style_set_value_str(&button_resume_s0,LV_STATE_DEFAULT,button_resume_LV_STYLE_VALUE_STR_part_0_state_0);
	lv_style_set_value_color(&button_resume_s0,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_value_font(&button_resume_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(1,162,177)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&button_resume_s0,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&button_resume_s0,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&button_resume_s0,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&button_resume_s0,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0xbc,LV_COLOR_MAKE(204,236,239)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&button_resume_s0,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_bg_color(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_outline_color(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_shadow_color(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_pattern_recolor(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_value_color(&button_resume_s0,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_obj_t *button_resume = lv_btn_create(parent, NULL);
	lv_obj_set_hidden(button_resume, false);
	lv_obj_set_click(button_resume, true);
	lv_obj_set_drag(button_resume, false);
	lv_obj_set_pos(button_resume, 5, 5);
	lv_obj_set_size(button_resume, 100, 39);
	lv_btn_set_checkable(button_resume, false);
	lv_btn_set_fit(button_resume, LV_FIT_NONE);
	lv_obj_add_style(button_resume, 0, &button_resume_s0);

	button_resume_scr_screenmain = button_resume;
	lv_obj_set_event_cb(button_resume_scr_screenmain, btn_resume_event_callback);


	static lv_style_t container_1_s0;
	lv_style_init(&container_1_s0);
	lv_style_set_bg_color(&container_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_bg_color(&container_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_CHECKED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_bg_color(&container_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_bg_color(&container_1_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_EDITED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_bg_color(&container_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_HOVERED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_bg_color(&container_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_PRESSED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_style_set_bg_color(&container_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&container_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&container_1_s0,LV_STATE_DISABLED,COLOR_PICK(0xe9,LV_COLOR_MAKE(221,221,221)));
	lv_obj_t *container_1 = lv_cont_create(parent, NULL);
	lv_obj_set_hidden(container_1, false);
	lv_obj_set_click(container_1, true);
	lv_obj_set_drag(container_1, false);
	lv_obj_set_pos(container_1, 2, 203);
	lv_obj_set_size(container_1, 320, 37);
	lv_cont_set_layout(container_1, LV_LAYOUT_ROW_MID);
	lv_obj_add_style(container_1, 0, &container_1_s0);

	container_1_scr_screenmain = container_1;


	static lv_style_t label_1_s0;
	lv_style_init(&label_1_s0);
	lv_style_set_bg_color(&label_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_font(&label_1_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_1_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_1_s0,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_1_s0,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_1_s0,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_obj_t *label_1 = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_1, false);
	lv_obj_set_click(label_1, false);
	lv_obj_set_drag(label_1, false);
	lv_plugin_label_allocate_ext_attr(label_1);
	lv_label_set_text(label_1,"Result:");
	lv_obj_set_pos(label_1, 14, 10);
	lv_obj_set_size(label_1, 57, 17);
	lv_obj_add_style(label_1, 0, &label_1_s0);

	label_1_scr_screenmain = label_1;


	static lv_style_t label_2_s0;
	lv_style_init(&label_2_s0);
	lv_style_set_bg_color(&label_2_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_DEFAULT,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_DEFAULT,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_font(&label_2_s0,LV_STATE_DEFAULT,&notosans_black_16_1bpp);
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_DEFAULT,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_DEFAULT,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_2_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_CHECKED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_CHECKED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_CHECKED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_CHECKED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_2_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_FOCUSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_FOCUSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_FOCUSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_FOCUSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_2_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_EDITED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_EDITED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_EDITED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_EDITED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_2_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_HOVERED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_HOVERED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_HOVERED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_HOVERED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_2_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_PRESSED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_PRESSED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_PRESSED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_PRESSED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_style_set_bg_color(&label_2_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_bg_grad_color(&label_2_s0,LV_STATE_DISABLED,COLOR_PICK(0x2,LV_COLOR_MAKE(255,255,255)));
	lv_style_set_border_color(&label_2_s0,LV_STATE_DISABLED,COLOR_PICK(0x1,LV_COLOR_MAKE(0,0,0)));
	lv_style_set_text_color(&label_2_s0,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_color(&label_2_s0,LV_STATE_DISABLED,COLOR_PICK(0xd3,LV_COLOR_MAKE(60,60,60)));
	lv_style_set_text_sel_bg_color(&label_2_s0,LV_STATE_DISABLED,COLOR_PICK(0x3a,LV_COLOR_MAKE(0,180,149)));
	lv_obj_t *label_2 = lv_label_create(container_1, NULL);
	lv_obj_set_hidden(label_2, false);
	lv_obj_set_click(label_2, false);
	lv_obj_set_drag(label_2, false);
	lv_plugin_label_allocate_ext_attr(label_2);
	lv_label_set_text(label_2,"Text");
	lv_label_set_long_mode(label_2, LV_LABEL_LONG_SROLL_CIRC);
	lv_obj_set_pos(label_2, 83, 9);
	lv_obj_set_size(label_2, 101, 18);
	lv_obj_add_style(label_2, 0, &label_2_s0);

	label_2_scr_screenmain = label_2;


	return parent;
}
